# Generated by Django 3.1.3 on 2020-11-12 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('qr_code', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('m_traveled', models.FloatField()),
                ('is_locked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BipMobike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cyclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12)),
                ('dv', models.CharField(max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField()),
                ('time_in_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.bicycle')),
                ('cyclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.cyclist')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_rating', models.IntegerField()),
                ('bicycle_rating', models.IntegerField()),
                ('parking_lot_rating', models.IntegerField()),
                ('general_comment', models.CharField(max_length=500)),
                ('route', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.route')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='api.route')),
            ],
        ),
    ]
