# Generated by Django 3.1.3 on 2020-11-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefee',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='starting_date',
            field=models.DateTimeField(null=True),
        ),
    ]
