# Generated by Django 3.1.3 on 2020-11-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201111_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipmobike',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cyclist'),
        ),
    ]
