# Generated by Django 3.1.3 on 2020-11-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201113_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='m_traveled',
            field=models.FloatField(default=0),
        ),
    ]
