# Generated by Django 3.1.3 on 2020-11-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201116_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='maxCapacity',
            new_name='max_capacity',
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bicycles', to='api.parkinglot'),
        ),
    ]
